/* tslint:disable */
/* eslint-disable */
/**
 * HireSense (知聘) - Backend
 * HireSense 后端接口，涵盖了用户鉴权、档案管理、实时沉浸式面试交互以及多维度面试报告生成等核心能力。
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 维度级解释详情
 */
export interface DimensionDetail {
    /**
     * 维度分（十分制）
     */
    'score': number;
    /**
     * 该维度的一句话总结
     */
    'summary': string;
    /**
     * 该维度下答到的证据点
     */
    'strength_points': Array<string>;
    /**
     * 该维度下缺失的证据点
     */
    'missing_points': Array<string>;
}
/**
 * 单场面试的模型表示
 */
export interface Interview {
    /**
     * 场次唯一 ID
     */
    'id': string;
    'mode': InterviewMode;
    /**
     * 当前面试所处的流程状态
     */
    'status': InterviewStatusEnum;
    /**
     * 开启面试的时间戳（毫秒）
     */
    'created_at': number;
    /**
     * 面试一旦完成后附加的总结评估分析，若未结束可能为空
     */
    'report'?: Report;
}

export const InterviewStatusEnum = {
    Started: 'started',
    Stopped: 'stopped'
} as const;

export type InterviewStatusEnum = typeof InterviewStatusEnum[keyof typeof InterviewStatusEnum];

/**
 * 面试模式
 */

export const InterviewMode = {
    Single: 'single',
    PanelTrio: 'panel_trio'
} as const;

export type InterviewMode = typeof InterviewMode[keyof typeof InterviewMode];


/**
 * 候选人的面试回答
 */
export interface InterviewReplyRequest {
    /**
     * 针对上一轮面试官提问的用户答案
     */
    'text': string;
}
export interface InterviewReplyResponse {
    'success': boolean;
    'message': string;
    'data': InterviewReplyResponseData;
}
export interface InterviewReplyResponseData {
    /**
     * AI 面试官作出的回应以及下一轮追问
     */
    'reply': string;
    /**
     * 面试是否结束
     */
    'ending': boolean;
    'mode': InterviewMode;
    'speaker_role': InterviewSpeakerRole;
}


/**
 * 发言的 AI 面试官角色
 */

export const InterviewSpeakerRole = {
    Ai: 'ai',
    Hr: 'hr',
    TechLead: 'tech_lead',
    Executive: 'executive'
} as const;

export type InterviewSpeakerRole = typeof InterviewSpeakerRole[keyof typeof InterviewSpeakerRole];


export interface InterviewStartRequest {
    'mode'?: InterviewMode;
}


export interface InterviewStartResponse {
    'success': boolean;
    'message': string;
    'data': InterviewStartResponseData;
}
export interface InterviewStartResponseData {
    /**
     * 新创建的本次面试 ID
     */
    'id': string;
    /**
     * AI 面试官返回的首个问题
     */
    'reply': string;
    'mode': InterviewMode;
    'speaker_role': InterviewSpeakerRole;
}


export interface InterviewStopRequest {
    /**
     * 需要终止的面试 ID
     */
    'id': string;
}
export interface InterviewStopResponse {
    'success': boolean;
    'message': string;
    'data': any;
}
export interface InterviewsResponse {
    'success': boolean;
    'message': string;
    'data': Array<Interview>;
}
/**
 * 用户详细职业档案和 AI 调优设定
 */
export interface Profile {
    /**
     * 姓名
     */
    'name': string;
    /**
     * 投递或期望的职位角色
     */
    'job': ProfileJobEnum;
    /**
     * 结构化的简历文本
     */
    'resume'?: string;
    /**
     * 专门下达给 AI 面试官的人设或追问偏好指令
     */
    'personalization'?: string;
}

export const ProfileJobEnum = {
    Frontend: 'frontend',
    Backend: 'backend'
} as const;

export type ProfileJobEnum = typeof ProfileJobEnum[keyof typeof ProfileJobEnum];

export interface ProfileResponse {
    'success': boolean;
    'message': string;
    'data': Profile;
}
export interface PutProfileResponse {
    'success': boolean;
    'message': string;
    'data': any;
}
/**
 * 添加面试报告请求体
 */
export interface PutReportRequest {
    /**
     * 后端系统的服务间通信校验密钥
     */
    'secret': string;
    /**
     * 面试 ID
     */
    'id': string;
    'report': Report;
}
export interface PutReportResponse {
    'success': boolean;
    'message': string;
    'data': any;
}
/**
 * AI 面试综合复盘报告
 */
export interface Report {
    /**
     * 本场面试的岗位类型
     */
    'job': ReportJobEnum;
    'mode': InterviewMode;
    /**
     * 总评分（百分制）
     */
    'score': number;
    /**
     * 通用能力评分评估（十分制）
     */
    'general': { [key: string]: number; };
    /**
     * 通用能力维度的结构化解释
     */
    'general_details': { [key: string]: DimensionDetail; };
    /**
     * 专业能力硬性技能打分（十分制）
     */
    'specific': { [key: string]: number; };
    /**
     * 岗位维度的结构化解释
     */
    'specific_details': { [key: string]: DimensionDetail; };
    /**
     * 面试表现综合反馈
     */
    'feedback': string;
    /**
     * 短板与不足总结
     */
    'shortcomings': Array<string>;
    /**
     * 后续改进建议
     */
    'advice': string;
    /**
     * 推荐学习资源
     */
    'resources': Array<string>;
    /**
     * 逐轮复盘（重点展示需要改进的回合）
     */
    'reviews': Array<ReportReview>;
}

export const ReportJobEnum = {
    Backend: 'backend',
    Frontend: 'frontend'
} as const;

export type ReportJobEnum = typeof ReportJobEnum[keyof typeof ReportJobEnum];

/**
 * 单轮问答微观复盘详情
 */
export interface ReportReview {
    /**
     * 面试官问题
     */
    'interviewer': string;
    'interviewer_role': InterviewSpeakerRole;
    /**
     * 求职者的实际回答
     */
    'interviewee': string;
    /**
     * 该轮得分
     */
    'score': number;
    /**
     * AI 点评与纠误建议
     */
    'advice': string;
    /**
     * 当前题目的考点
     */
    'concept'?: string;
    /**
     * 当前题目的难度标签
     */
    'difficulty_label': string;
    'score_breakdown': ScoreBreakdown;
    /**
     * 支撑该分数的机器标签
     */
    'reason_tags': Array<string>;
    /**
     * 本题回答中已经答到的点
     */
    'strength_points': Array<string>;
    /**
     * 本题回答中缺失的点
     */
    'missing_points': Array<string>;
    /**
     * 对题级分数的结构化解释
     */
    'score_rationale': string;
}


export interface ResumeAnalysis {
    /**
     * 结果结构版本
     */
    'version': string;
    /**
     * 当前简历对应岗位
     */
    'job': ResumeAnalysisJobEnum;
    /**
     * 分析结果生成时间
     */
    'generated_at': string;
    /**
     * 对整份简历的整体总结
     */
    'summary': string;
    /**
     * 简历整体观感
     */
    'overall_tone'?: string;
    'blocks': Array<ResumeAnalysisBlock>;
}

export const ResumeAnalysisJobEnum = {
    Frontend: 'frontend',
    Backend: 'backend'
} as const;

export type ResumeAnalysisJobEnum = typeof ResumeAnalysisJobEnum[keyof typeof ResumeAnalysisJobEnum];

export interface ResumeAnalysisBlock {
    /**
     * 简历分块唯一 ID
     */
    'id': string;
    /**
     * 分块原始文本
     */
    'text': string;
    'label': ResumeAnalysisLabel;
    /**
     * 该分块为什么被这样标注
     */
    'reason'?: string;
    'highlight_phrases'?: Array<ResumeAnalysisHighlightPhrase>;
    'callout'?: ResumeAnalysisCallout;
}


export interface ResumeAnalysisCallout {
    /**
     * 批注标题
     */
    'title'?: string;
    /**
     * 批注正文
     */
    'body': string;
}
export interface ResumeAnalysisHighlightPhrase {
    /**
     * 需要被单独高亮的原文短语
     */
    'text': string;
    'label': ResumeAnalysisLabel;
    /**
     * 对该高亮短语的简短说明
     */
    'comment'?: string;
}


/**
 * 简历段落或短语的高亮等级
 */

export const ResumeAnalysisLabel = {
    Strength: 'strength',
    Probe: 'probe',
    Risk: 'risk',
    Neutral: 'neutral'
} as const;

export type ResumeAnalysisLabel = typeof ResumeAnalysisLabel[keyof typeof ResumeAnalysisLabel];


export interface ResumeAnalysisLookupPayload {
    'analysis'?: ResumeAnalysis;
}
export interface ResumeAnalysisLookupResponse {
    'success': boolean;
    'message': string;
    'data': ResumeAnalysisLookupPayload;
}
export interface ResumeAnalysisResponse {
    'success': boolean;
    'message': string;
    'data': ResumeAnalysis;
}
/**
 * 题级分项得分
 */
export interface ScoreBreakdown {
    /**
     * 对标准答案主线的覆盖度
     */
    'coverage_score': number;
    /**
     * 回答内部与标准答案的一致性
     */
    'consistency_score': number;
    /**
     * 对关键点和边界条件的完整度
     */
    'completeness_score': number;
}
/**
 * 登录请求实体
 */
export interface SignInRequest {
    /**
     * 账号
     */
    'account': string;
    /**
     * 密码
     */
    'password': string;
}
export interface SignInResponse {
    'success': boolean;
    'message': string;
    /**
     * Access Token
     */
    'data': string;
}
export interface SignOutResponse {
    'success': boolean;
    'message': string;
    'data': any;
}
/**
 * 注册请求体
 */
export interface SignUpRequest {
    /**
     * 账号
     */
    'account': string;
    /**
     * 用户名
     */
    'name': string;
    /**
     * 密码
     */
    'password': string;
}
export interface SignUpResponse {
    'success': boolean;
    'message': string;
    /**
     * Access Token
     */
    'data': string;
}
export interface UserPasswordRequest {
    /**
     * 新密码
     */
    'password': string;
}
export interface UserPasswordResponse {
    'success': boolean;
    'message': string;
    'data': any;
}

/**
 * AuthenticationApi - axios parameter creator
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 使用已注册的账号密码进行身份验证，换取 JWT。
         * @summary 登录
         * @param {SignInRequest} [signInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSigninPost: async (signInRequest?: SignInRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/signin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 吊销当前 Token，安全退出账号体系。
         * @summary 注销
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSignoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/signout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 提交基本信息创建 HireSense 平台账号。
         * @summary 注册
         * @param {SignUpRequest} [signUpRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSignupPost: async (signUpRequest?: SignUpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * 使用已注册的账号密码进行身份验证，换取 JWT。
         * @summary 登录
         * @param {SignInRequest} [signInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthSigninPost(signInRequest?: SignInRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignInResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthSigninPost(signInRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiAuthSigninPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 吊销当前 Token，安全退出账号体系。
         * @summary 注销
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthSignoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignOutResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthSignoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiAuthSignoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 提交基本信息创建 HireSense 平台账号。
         * @summary 注册
         * @param {SignUpRequest} [signUpRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthSignupPost(signUpRequest?: SignUpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignUpResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthSignupPost(signUpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiAuthSignupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * 使用已注册的账号密码进行身份验证，换取 JWT。
         * @summary 登录
         * @param {SignInRequest} [signInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSigninPost(signInRequest?: SignInRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignInResponse> {
            return localVarFp.apiAuthSigninPost(signInRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 吊销当前 Token，安全退出账号体系。
         * @summary 注销
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSignoutPost(options?: RawAxiosRequestConfig): AxiosPromise<SignOutResponse> {
            return localVarFp.apiAuthSignoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 提交基本信息创建 HireSense 平台账号。
         * @summary 注册
         * @param {SignUpRequest} [signUpRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSignupPost(signUpRequest?: SignUpRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignUpResponse> {
            return localVarFp.apiAuthSignupPost(signUpRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 使用已注册的账号密码进行身份验证，换取 JWT。
     * @summary 登录
     * @param {SignInRequest} [signInRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthSigninPost(signInRequest?: SignInRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthSigninPost(signInRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 吊销当前 Token，安全退出账号体系。
     * @summary 注销
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthSignoutPost(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthSignoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 提交基本信息创建 HireSense 平台账号。
     * @summary 注册
     * @param {SignUpRequest} [signUpRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthSignupPost(signUpRequest?: SignUpRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthSignupPost(signUpRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * InterviewApi - axios parameter creator
 */
export const InterviewApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 提交候选人录制的音频流或者直接提交文本，AI面试官会进行意图分析并进行下一轮追问。
         * @summary 生成面试官回复
         * @param {string} id 当前进行的面试场次唯一 ID
         * @param {InterviewReplyRequest} [interviewReplyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewReplyPost: async (id: string, interviewReplyRequest?: InterviewReplyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiInterviewReplyPost', 'id', id)
            const localVarPath = `/api/interview/reply`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(interviewReplyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * AI 完成总结后通过系统级通讯向该条目补充完整的评估报告记录。（供内部微服务/Webhooks通信专用）
         * @summary 添加面试的报告
         * @param {PutReportRequest} [putReportRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewReportPut: async (putReportRequest?: PutReportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/interview/report`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putReportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 基于用户当前档案数据生成并启动一个新的 AI 面试会话，并获取首个提问。
         * @summary 开始一场面试
         * @param {InterviewStartRequest} [interviewStartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewStartPost: async (interviewStartRequest?: InterviewStartRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/interview/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(interviewStartRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 候选人主动放弃或时间耗尽时调用，停止计费并中止本次会话进程。（通常在系统判断回答 ending=true 时无需显式调用）
         * @summary 结束一场面试
         * @param {InterviewStopRequest} [interviewStopRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewStopPost: async (interviewStopRequest?: InterviewStopRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/interview/stop`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(interviewStopRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InterviewApi - functional programming interface
 */
export const InterviewApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InterviewApiAxiosParamCreator(configuration)
    return {
        /**
         * 提交候选人录制的音频流或者直接提交文本，AI面试官会进行意图分析并进行下一轮追问。
         * @summary 生成面试官回复
         * @param {string} id 当前进行的面试场次唯一 ID
         * @param {InterviewReplyRequest} [interviewReplyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInterviewReplyPost(id: string, interviewReplyRequest?: InterviewReplyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InterviewReplyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInterviewReplyPost(id, interviewReplyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InterviewApi.apiInterviewReplyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * AI 完成总结后通过系统级通讯向该条目补充完整的评估报告记录。（供内部微服务/Webhooks通信专用）
         * @summary 添加面试的报告
         * @param {PutReportRequest} [putReportRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInterviewReportPut(putReportRequest?: PutReportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInterviewReportPut(putReportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InterviewApi.apiInterviewReportPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 基于用户当前档案数据生成并启动一个新的 AI 面试会话，并获取首个提问。
         * @summary 开始一场面试
         * @param {InterviewStartRequest} [interviewStartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInterviewStartPost(interviewStartRequest?: InterviewStartRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InterviewStartResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInterviewStartPost(interviewStartRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InterviewApi.apiInterviewStartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 候选人主动放弃或时间耗尽时调用，停止计费并中止本次会话进程。（通常在系统判断回答 ending=true 时无需显式调用）
         * @summary 结束一场面试
         * @param {InterviewStopRequest} [interviewStopRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInterviewStopPost(interviewStopRequest?: InterviewStopRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InterviewStopResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInterviewStopPost(interviewStopRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InterviewApi.apiInterviewStopPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InterviewApi - factory interface
 */
export const InterviewApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InterviewApiFp(configuration)
    return {
        /**
         * 提交候选人录制的音频流或者直接提交文本，AI面试官会进行意图分析并进行下一轮追问。
         * @summary 生成面试官回复
         * @param {string} id 当前进行的面试场次唯一 ID
         * @param {InterviewReplyRequest} [interviewReplyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewReplyPost(id: string, interviewReplyRequest?: InterviewReplyRequest, options?: RawAxiosRequestConfig): AxiosPromise<InterviewReplyResponse> {
            return localVarFp.apiInterviewReplyPost(id, interviewReplyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * AI 完成总结后通过系统级通讯向该条目补充完整的评估报告记录。（供内部微服务/Webhooks通信专用）
         * @summary 添加面试的报告
         * @param {PutReportRequest} [putReportRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewReportPut(putReportRequest?: PutReportRequest, options?: RawAxiosRequestConfig): AxiosPromise<PutReportResponse> {
            return localVarFp.apiInterviewReportPut(putReportRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 基于用户当前档案数据生成并启动一个新的 AI 面试会话，并获取首个提问。
         * @summary 开始一场面试
         * @param {InterviewStartRequest} [interviewStartRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewStartPost(interviewStartRequest?: InterviewStartRequest, options?: RawAxiosRequestConfig): AxiosPromise<InterviewStartResponse> {
            return localVarFp.apiInterviewStartPost(interviewStartRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 候选人主动放弃或时间耗尽时调用，停止计费并中止本次会话进程。（通常在系统判断回答 ending=true 时无需显式调用）
         * @summary 结束一场面试
         * @param {InterviewStopRequest} [interviewStopRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewStopPost(interviewStopRequest?: InterviewStopRequest, options?: RawAxiosRequestConfig): AxiosPromise<InterviewStopResponse> {
            return localVarFp.apiInterviewStopPost(interviewStopRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InterviewApi - object-oriented interface
 */
export class InterviewApi extends BaseAPI {
    /**
     * 提交候选人录制的音频流或者直接提交文本，AI面试官会进行意图分析并进行下一轮追问。
     * @summary 生成面试官回复
     * @param {string} id 当前进行的面试场次唯一 ID
     * @param {InterviewReplyRequest} [interviewReplyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiInterviewReplyPost(id: string, interviewReplyRequest?: InterviewReplyRequest, options?: RawAxiosRequestConfig) {
        return InterviewApiFp(this.configuration).apiInterviewReplyPost(id, interviewReplyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * AI 完成总结后通过系统级通讯向该条目补充完整的评估报告记录。（供内部微服务/Webhooks通信专用）
     * @summary 添加面试的报告
     * @param {PutReportRequest} [putReportRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiInterviewReportPut(putReportRequest?: PutReportRequest, options?: RawAxiosRequestConfig) {
        return InterviewApiFp(this.configuration).apiInterviewReportPut(putReportRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 基于用户当前档案数据生成并启动一个新的 AI 面试会话，并获取首个提问。
     * @summary 开始一场面试
     * @param {InterviewStartRequest} [interviewStartRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiInterviewStartPost(interviewStartRequest?: InterviewStartRequest, options?: RawAxiosRequestConfig) {
        return InterviewApiFp(this.configuration).apiInterviewStartPost(interviewStartRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 候选人主动放弃或时间耗尽时调用，停止计费并中止本次会话进程。（通常在系统判断回答 ending=true 时无需显式调用）
     * @summary 结束一场面试
     * @param {InterviewStopRequest} [interviewStopRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiInterviewStopPost(interviewStopRequest?: InterviewStopRequest, options?: RawAxiosRequestConfig) {
        return InterviewApiFp(this.configuration).apiInterviewStopPost(interviewStopRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 列出过去参与的所有 AI 面试场次、报告状态及简要概览。
         * @summary 获取所有历史面试记录
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserInterviewsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/interviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 更新当前登录用户的账户密码。
         * @summary 修改密码
         * @param {UserPasswordRequest} [userPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPasswordPut: async (userPasswordRequest?: UserPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 读取当前求职者的基本信息、简历内容以及 AI 面试官倾向设置。
         * @summary 获取用户档案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserProfileGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 覆写求职者档案，例如更新期望岗位、打磨后的简历以及面试难度配置。
         * @summary 更新用户档案
         * @param {Profile} [profile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserProfilePut: async (profile?: Profile, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profile, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 读取当前登录用户最近一次已保存的彩色高亮版简历分析结果。
         * @summary 获取最近一次简历分析
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserResumeAnalysisGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/resume-analysis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 基于当前登录用户已保存的岗位和简历文本，生成并保存最近一次彩色高亮版简历分析。
         * @summary 生成简历分析
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserResumeAnalysisPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/resume-analysis`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 列出过去参与的所有 AI 面试场次、报告状态及简要概览。
         * @summary 获取所有历史面试记录
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserInterviewsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InterviewsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserInterviewsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserInterviewsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 更新当前登录用户的账户密码。
         * @summary 修改密码
         * @param {UserPasswordRequest} [userPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserPasswordPut(userPasswordRequest?: UserPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserPasswordResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserPasswordPut(userPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserPasswordPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 读取当前求职者的基本信息、简历内容以及 AI 面试官倾向设置。
         * @summary 获取用户档案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserProfileGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserProfileGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserProfileGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 覆写求职者档案，例如更新期望岗位、打磨后的简历以及面试难度配置。
         * @summary 更新用户档案
         * @param {Profile} [profile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserProfilePut(profile?: Profile, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserProfilePut(profile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserProfilePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 读取当前登录用户最近一次已保存的彩色高亮版简历分析结果。
         * @summary 获取最近一次简历分析
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserResumeAnalysisGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResumeAnalysisLookupResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserResumeAnalysisGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserResumeAnalysisGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 基于当前登录用户已保存的岗位和简历文本，生成并保存最近一次彩色高亮版简历分析。
         * @summary 生成简历分析
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserResumeAnalysisPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResumeAnalysisResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserResumeAnalysisPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserResumeAnalysisPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 列出过去参与的所有 AI 面试场次、报告状态及简要概览。
         * @summary 获取所有历史面试记录
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserInterviewsGet(options?: RawAxiosRequestConfig): AxiosPromise<InterviewsResponse> {
            return localVarFp.apiUserInterviewsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 更新当前登录用户的账户密码。
         * @summary 修改密码
         * @param {UserPasswordRequest} [userPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPasswordPut(userPasswordRequest?: UserPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserPasswordResponse> {
            return localVarFp.apiUserPasswordPut(userPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 读取当前求职者的基本信息、简历内容以及 AI 面试官倾向设置。
         * @summary 获取用户档案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserProfileGet(options?: RawAxiosRequestConfig): AxiosPromise<ProfileResponse> {
            return localVarFp.apiUserProfileGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 覆写求职者档案，例如更新期望岗位、打磨后的简历以及面试难度配置。
         * @summary 更新用户档案
         * @param {Profile} [profile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserProfilePut(profile?: Profile, options?: RawAxiosRequestConfig): AxiosPromise<PutProfileResponse> {
            return localVarFp.apiUserProfilePut(profile, options).then((request) => request(axios, basePath));
        },
        /**
         * 读取当前登录用户最近一次已保存的彩色高亮版简历分析结果。
         * @summary 获取最近一次简历分析
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserResumeAnalysisGet(options?: RawAxiosRequestConfig): AxiosPromise<ResumeAnalysisLookupResponse> {
            return localVarFp.apiUserResumeAnalysisGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 基于当前登录用户已保存的岗位和简历文本，生成并保存最近一次彩色高亮版简历分析。
         * @summary 生成简历分析
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserResumeAnalysisPost(options?: RawAxiosRequestConfig): AxiosPromise<ResumeAnalysisResponse> {
            return localVarFp.apiUserResumeAnalysisPost(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 列出过去参与的所有 AI 面试场次、报告状态及简要概览。
     * @summary 获取所有历史面试记录
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserInterviewsGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserInterviewsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 更新当前登录用户的账户密码。
     * @summary 修改密码
     * @param {UserPasswordRequest} [userPasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserPasswordPut(userPasswordRequest?: UserPasswordRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserPasswordPut(userPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 读取当前求职者的基本信息、简历内容以及 AI 面试官倾向设置。
     * @summary 获取用户档案
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserProfileGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserProfileGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 覆写求职者档案，例如更新期望岗位、打磨后的简历以及面试难度配置。
     * @summary 更新用户档案
     * @param {Profile} [profile] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserProfilePut(profile?: Profile, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserProfilePut(profile, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 读取当前登录用户最近一次已保存的彩色高亮版简历分析结果。
     * @summary 获取最近一次简历分析
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserResumeAnalysisGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserResumeAnalysisGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 基于当前登录用户已保存的岗位和简历文本，生成并保存最近一次彩色高亮版简历分析。
     * @summary 生成简历分析
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserResumeAnalysisPost(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserResumeAnalysisPost(options).then((request) => request(this.axios, this.basePath));
    }
}



