/* tslint:disable */
/* eslint-disable */
/**
 * HireSense (知聘) - Backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface Interview {
    'id': string;
    /**
     * 时间戳（毫秒）
     */
    'created_at': number;
    'status': InterviewStatusEnum;
    'report'?: Report;
}

export const InterviewStatusEnum = {
    Started: 'started',
    Stopped: 'stopped'
} as const;

export type InterviewStatusEnum = typeof InterviewStatusEnum[keyof typeof InterviewStatusEnum];

export interface InterviewReplyRequest {
    'text': string;
}
export interface InterviewReplyResponse {
    'success': boolean;
    'message': string;
    'data': InterviewReplyResponseData;
}
export interface InterviewReplyResponseData {
    'reply': string;
    /**
     * 面试是否结束
     */
    'ending': boolean;
}
export interface InterviewStartResponse {
    'success': boolean;
    'message': string;
    'data': InterviewStartResponseData;
}
export interface InterviewStartResponseData {
    'id': string;
}
export interface InterviewStopRequest {
    'id': string;
}
export interface InterviewStopResponse {
    'success': boolean;
    'message': string;
    'data': any;
}
export interface InterviewsResponse {
    'success': boolean;
    'message': string;
    'data': Array<Interview>;
}
export interface Profile {
    'name'?: string;
    'job'?: string;
    'resume'?: string;
    'personalization'?: string;
}
export interface ProfileResponse {
    'success': boolean;
    'message': string;
    'data': Profile;
}
export interface PutProfileResponse {
    'success': boolean;
    'message': string;
    'data': any;
}
export interface PutReportRequest {
    'secret': string;
    'id': string;
    'report': Report;
}
export interface PutReportResponse {
    'success': boolean;
    'message': string;
    'data': any;
}
export interface Report {
    /**
     * 总评分
     */
    'score': number;
    /**
     * 通用能力评分
     */
    'general': { [key: string]: number; };
    /**
     * 专业能力评分
     */
    'specific': { [key: string]: number; };
    /**
     * 面试表现反馈
     */
    'feedback': string;
    /**
     * 短板
     */
    'shortcomings': Array<string>;
    /**
     * 改进建议
     */
    'advice': string;
    /**
     * 学习资源
     */
    'resources': Array<string>;
    'reviews': Array<ReportReviewsInner>;
}
/**
 * 逐轮复盘（只展示低于75分的问题）
 */
export interface ReportReviewsInner {
    'interviewer': string;
    'interviewee': string;
    'score': number;
    'advice': string;
}
export interface SignInRequest {
    'account': string;
    'password': string;
}
export interface SignInResponse {
    'success': boolean;
    'message': string;
    /**
     * Access Token
     */
    'data': string;
}
export interface SignOutResponse {
    'success': boolean;
    'message': string;
    'data': any;
}
export interface SignUpRequest {
    'name': string;
    'account': string;
    'password': string;
}
export interface SignUpResponse {
    'success': boolean;
    'message': string;
    /**
     * Access Token
     */
    'data': string;
}
export interface UserPasswordRequest {
    'password': string;
}
export interface UserPasswordResponse {
    'success': boolean;
    'message': string;
    'data': any;
}

/**
 * AuthenticationApi - axios parameter creator
 */
export const AuthenticationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 登录
         * @param {SignInRequest} [signInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSigninPost: async (signInRequest?: SignInRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/signin`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signInRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 注销
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSignoutPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/signout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 注册
         * @param {SignUpRequest} [signUpRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSignupPost: async (signUpRequest?: SignUpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/auth/signup`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signUpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthenticationApi - functional programming interface
 */
export const AuthenticationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthenticationApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 登录
         * @param {SignInRequest} [signInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthSigninPost(signInRequest?: SignInRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignInResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthSigninPost(signInRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiAuthSigninPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 注销
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthSignoutPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignOutResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthSignoutPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiAuthSignoutPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 注册
         * @param {SignUpRequest} [signUpRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthSignupPost(signUpRequest?: SignUpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SignUpResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthSignupPost(signUpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthenticationApi.apiAuthSignupPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthenticationApi - factory interface
 */
export const AuthenticationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthenticationApiFp(configuration)
    return {
        /**
         * 
         * @summary 登录
         * @param {SignInRequest} [signInRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSigninPost(signInRequest?: SignInRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignInResponse> {
            return localVarFp.apiAuthSigninPost(signInRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 注销
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSignoutPost(options?: RawAxiosRequestConfig): AxiosPromise<SignOutResponse> {
            return localVarFp.apiAuthSignoutPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 注册
         * @param {SignUpRequest} [signUpRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthSignupPost(signUpRequest?: SignUpRequest, options?: RawAxiosRequestConfig): AxiosPromise<SignUpResponse> {
            return localVarFp.apiAuthSignupPost(signUpRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthenticationApi - object-oriented interface
 */
export class AuthenticationApi extends BaseAPI {
    /**
     * 
     * @summary 登录
     * @param {SignInRequest} [signInRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthSigninPost(signInRequest?: SignInRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthSigninPost(signInRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 注销
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthSignoutPost(options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthSignoutPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 注册
     * @param {SignUpRequest} [signUpRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiAuthSignupPost(signUpRequest?: SignUpRequest, options?: RawAxiosRequestConfig) {
        return AuthenticationApiFp(this.configuration).apiAuthSignupPost(signUpRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * InterviewApi - axios parameter creator
 */
export const InterviewApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 生成面试官回复
         * @param {string} id 
         * @param {InterviewReplyRequest} [interviewReplyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewReplyPost: async (id: string, interviewReplyRequest?: InterviewReplyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiInterviewReplyPost', 'id', id)
            const localVarPath = `/api/interview/reply`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (id !== undefined) {
                localVarQueryParameter['id'] = id;
            }

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(interviewReplyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 添加面试的报告
         * @param {PutReportRequest} [putReportRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewReportPut: async (putReportRequest?: PutReportRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/interview/report`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putReportRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 开始一场面试
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewStartPost: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/interview/start`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 结束一场面试
         * @param {InterviewStopRequest} [interviewStopRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewStopPost: async (interviewStopRequest?: InterviewStopRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/interview/stop`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(interviewStopRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * InterviewApi - functional programming interface
 */
export const InterviewApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = InterviewApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 生成面试官回复
         * @param {string} id 
         * @param {InterviewReplyRequest} [interviewReplyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInterviewReplyPost(id: string, interviewReplyRequest?: InterviewReplyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InterviewReplyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInterviewReplyPost(id, interviewReplyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InterviewApi.apiInterviewReplyPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 添加面试的报告
         * @param {PutReportRequest} [putReportRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInterviewReportPut(putReportRequest?: PutReportRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutReportResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInterviewReportPut(putReportRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InterviewApi.apiInterviewReportPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 开始一场面试
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInterviewStartPost(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InterviewStartResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInterviewStartPost(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InterviewApi.apiInterviewStartPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 结束一场面试
         * @param {InterviewStopRequest} [interviewStopRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiInterviewStopPost(interviewStopRequest?: InterviewStopRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InterviewStopResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiInterviewStopPost(interviewStopRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['InterviewApi.apiInterviewStopPost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * InterviewApi - factory interface
 */
export const InterviewApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = InterviewApiFp(configuration)
    return {
        /**
         * 
         * @summary 生成面试官回复
         * @param {string} id 
         * @param {InterviewReplyRequest} [interviewReplyRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewReplyPost(id: string, interviewReplyRequest?: InterviewReplyRequest, options?: RawAxiosRequestConfig): AxiosPromise<InterviewReplyResponse> {
            return localVarFp.apiInterviewReplyPost(id, interviewReplyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 添加面试的报告
         * @param {PutReportRequest} [putReportRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewReportPut(putReportRequest?: PutReportRequest, options?: RawAxiosRequestConfig): AxiosPromise<PutReportResponse> {
            return localVarFp.apiInterviewReportPut(putReportRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 开始一场面试
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewStartPost(options?: RawAxiosRequestConfig): AxiosPromise<InterviewStartResponse> {
            return localVarFp.apiInterviewStartPost(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 结束一场面试
         * @param {InterviewStopRequest} [interviewStopRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiInterviewStopPost(interviewStopRequest?: InterviewStopRequest, options?: RawAxiosRequestConfig): AxiosPromise<InterviewStopResponse> {
            return localVarFp.apiInterviewStopPost(interviewStopRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * InterviewApi - object-oriented interface
 */
export class InterviewApi extends BaseAPI {
    /**
     * 
     * @summary 生成面试官回复
     * @param {string} id 
     * @param {InterviewReplyRequest} [interviewReplyRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiInterviewReplyPost(id: string, interviewReplyRequest?: InterviewReplyRequest, options?: RawAxiosRequestConfig) {
        return InterviewApiFp(this.configuration).apiInterviewReplyPost(id, interviewReplyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 添加面试的报告
     * @param {PutReportRequest} [putReportRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiInterviewReportPut(putReportRequest?: PutReportRequest, options?: RawAxiosRequestConfig) {
        return InterviewApiFp(this.configuration).apiInterviewReportPut(putReportRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 开始一场面试
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiInterviewStartPost(options?: RawAxiosRequestConfig) {
        return InterviewApiFp(this.configuration).apiInterviewStartPost(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 结束一场面试
     * @param {InterviewStopRequest} [interviewStopRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiInterviewStopPost(interviewStopRequest?: InterviewStopRequest, options?: RawAxiosRequestConfig) {
        return InterviewApiFp(this.configuration).apiInterviewStopPost(interviewStopRequest, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserApi - axios parameter creator
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary 获取所有历史面试记录
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserInterviewsGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/interviews`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 修改密码
         * @param {UserPasswordRequest} [userPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPasswordPut: async (userPasswordRequest?: UserPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(userPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 获取用户档案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserProfileGet: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 更新用户档案
         * @param {Profile} [profile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserProfilePut: async (profile?: Profile, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/user/profile`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(profile, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary 获取所有历史面试记录
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserInterviewsGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<InterviewsResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserInterviewsGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserInterviewsGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 修改密码
         * @param {UserPasswordRequest} [userPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserPasswordPut(userPasswordRequest?: UserPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserPasswordResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserPasswordPut(userPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserPasswordPut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 获取用户档案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserProfileGet(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserProfileGet(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserProfileGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 更新用户档案
         * @param {Profile} [profile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiUserProfilePut(profile?: Profile, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PutProfileResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiUserProfilePut(profile, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.apiUserProfilePut']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 
         * @summary 获取所有历史面试记录
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserInterviewsGet(options?: RawAxiosRequestConfig): AxiosPromise<InterviewsResponse> {
            return localVarFp.apiUserInterviewsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 修改密码
         * @param {UserPasswordRequest} [userPasswordRequest] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserPasswordPut(userPasswordRequest?: UserPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserPasswordResponse> {
            return localVarFp.apiUserPasswordPut(userPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 获取用户档案
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserProfileGet(options?: RawAxiosRequestConfig): AxiosPromise<ProfileResponse> {
            return localVarFp.apiUserProfileGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 更新用户档案
         * @param {Profile} [profile] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiUserProfilePut(profile?: Profile, options?: RawAxiosRequestConfig): AxiosPromise<PutProfileResponse> {
            return localVarFp.apiUserProfilePut(profile, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 */
export class UserApi extends BaseAPI {
    /**
     * 
     * @summary 获取所有历史面试记录
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserInterviewsGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserInterviewsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 修改密码
     * @param {UserPasswordRequest} [userPasswordRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserPasswordPut(userPasswordRequest?: UserPasswordRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserPasswordPut(userPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 获取用户档案
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserProfileGet(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserProfileGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 更新用户档案
     * @param {Profile} [profile] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public apiUserProfilePut(profile?: Profile, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).apiUserProfilePut(profile, options).then((request) => request(this.axios, this.basePath));
    }
}



