openapi: 3.1.0
info:
  version: 1.0.0
  title: HireSense (知聘) - AI
servers:
  - url: http://127.0.0.1:8081
tags:
  - name: Interview
    description: 面试
paths:
  /api/interview/start:
    post:
      tags: [Interview]
      summary: 开始一场面试
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/InterviewStartRequest" }
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema: { $ref: "#/components/schemas/InterviewStatusResponse" }
  /api/interview/stop:
    post:
      tags: [Interview]
      summary: 结束一场面试
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/InterviewStopRequest" }
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema: { $ref: "#/components/schemas/InterviewStatusResponse" }
  /api/interview/reply:
    post:
      tags: [Interview]
      summary: 生成面试官回复
      requestBody:
        content:
          application/json:
            schema: { $ref: "#/components/schemas/InterviewReplyRequest" }
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema: { $ref: "#/components/schemas/InterviewReplyResponse" }
components:
  schemas:
    InterviewStartRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        resume:
          type: string
          description: 用户简历
        personalization:
          type: string
          description: 个性化面试官风格
      required: [id, resume, personalization]
    InterviewStopRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required: [id]
    InterviewStatusResponse:
      type: object
      properties:
        success: { type: boolean }
      required: [success]
    InputText:
      type: object
      properties:
        type: { const: "text" }
        content: { type: string }
      required: [type, content]
    InputTranscript:
      type: object
      properties:
        type: { const: "transcript" }
        content: { type: object } # TODO
      required: [type, content]
    InterviewReplyRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        input:
          type: object
          discriminator: { propertyName: type }
          oneOf:
            - $ref: "#/components/schemas/InputText"
            - $ref: "#/components/schemas/InputTranscript"
      required: [id, input]
    InterviewReplyResponse:
      type: object
      properties:
        reply: { type: string }
        ending:
          type: boolean
          description: "面试是否结束"
      required: [reply, ending]
